---
# tasks file for roles/db
- name: Show info about the env this host belongs to
  ansible.builtin.debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Include install_mongo.yml
  include_tasks: install_mongo.yml

- name: Include config_mongo.yml
  include_tasks: config_mongo.yml
