---
- name: Deploy App
  hosts: app
  tasks:
    - name: Install Git
      ansible.builtin.apt:
        name: git
        state: present
      become: true
    - name: Fetch the latest version of application code
      ansible.builtin.git:
        repo: 'https://github.com/express42/reddit.git'
        dest: "/home/{{ deploy_user }}/reddit"
        version: monolith
      become: true
      notify: Reload puma
    - name: Bundle install
      ansible.builtin.bundler:
        state: present
        chdir: "/home/{{ deploy_user }}/reddit"
    - name: Print URL
      ansible.builtin.debug:
        msg: "For check use http://{{ ansible_host }}:9292/"

  handlers:
    - name: Reload puma
      become: true
      ansible.builtin.systemd: name=puma state=restarted
