---
- name: Configure MongoDB
  hosts: db
  tags: db-tag
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
    - name: Change mongo config file
      ansible.builtin.template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: Restart mongod

  handlers:
  - name: Restart mongod
    ansible.builtin.service: name=mongod state=restarted

- name: Configure App
  hosts: app
  tags: app-tag
  become: true
  vars:
   db_host: 192.168.10.4
  tasks:
    - name: Add unit file for Puma
      ansible.builtin.copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: Reload puma

    - name: Add config for DB connection
      ansible.builtin.template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        owner: ubuntu
        group: ubuntu

    - name: Enable puma
      ansible.builtin.systemd: name=puma enabled=yes

  handlers:
  - name: Reload puma
    ansible.builtin.systemd: name=puma state=restarted

- name: Deploy App
  hosts: app
  tags: deploy-tag
  tasks:
    - name: Install Git
      ansible.builtin.apt:
        name: git
        state: present
      become: true
    - name: Fetch the latest version of application code
      ansible.builtin.git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      notify: Reload puma
    - name: Bundle install
      ansible.builtin.bundler:
        state: present
        chdir: /home/ubuntu/reddit
    - name: Print URL
      ansible.builtin.debug:
        msg: "For check use http://{{ ansible_host }}:9292/"

  handlers:
    - name: Reload puma
      become: true
      ansible.builtin.systemd: name=puma state=restarted
