---
- name: Create users
  hosts: all
  become: true

  vars_files:
    - "{{ inventory_dir }}/credentials.yml"

  tasks:
    - name: Create users
      ansible.builtin.user:
        name: "{{ item.key }}"
        password: "{{ item.value.password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
        groups: "{{ item.value.groups | default(omit) }}"
      with_dict: "{{ credentials.users }}"
