---
# tasks file for roles/app
- name: Show info about the env this host belongs to
  ansible.builtin.debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Include ruby.yml
  include_tasks: ruby.yml
- name: Include puma.yml
  include_tasks: puma.yml
