---
- name: Deploy App
  hosts: app
  tasks:
    - name: Install Git
      apt:
        name: git
        state: present
      become: true
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      notify: reload puma
    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit
    - name: Print URL
      debug:
        msg: "For check use http://{{ ansible_host }}:9292/"

  handlers:
    - name: reload puma
      become: true
      systemd: name=puma state=restarted
